apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: duj1rf7ev-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: duj1rf7ev-go 
  name: duj1rf7ev-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: duj1rf7ev-go 
